<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\Nodal.Migrations\Nodal.Migrations.csproj" />
    <ProjectReference Include="..\..\src\Nodal.Neo4j\Nodal.Neo4j.csproj" />
    <ProjectReference Include="..\..\src\Nodal.TigerGraph\Nodal.TigerGraph.csproj" />
  </ItemGroup>

</Project>
